#ifndef WIDGETSTYLE_GLOBAL_H
#define WIDGETSTYLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETSTYLE_LIBRARY)
#  define WIDGETSTYLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETSTYLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETSTYLE_GLOBAL_H
