#ifndef QWTHELPERS_GLOBAL_H
#define QWTHELPERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QWTHELPERS_LIBRARY)
#  define QWTHELPERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QWTHELPERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QWTHELPERS_GLOBAL_H
