#ifndef CUSTOMCURVES_GLOBAL_H
#define CUSTOMCURVES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOMCURVES_LIBRARY)
#  define CUSTOMCURVESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOMCURVESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOMCURVES_GLOBAL_H
