#ifndef ERRORMESSAGE_GLOBAL_H
#define ERRORMESSAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ERRORMESSAGE_LIBRARY)
#  define ERRORMESSAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ERRORMESSAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ERRORMESSAGE_GLOBAL_H
